#' Identify minima in a data frame
#'
#' Identify local extrema in a data frame
#'
#' @param df A \code{data.frame} generated by the \code{load.data} function.
#' @param threshold An integer defining threshold for local extrema identification
#'
#' @import dplyr
#' @import ggpmisc

identify.minima <- function(df, span = 11) {

    loc.minimum <- ggpmisc:::find_peaks(-df$close, span = span)

    df.extr <- dplyr::mutate(df, minimum = "no")

    df.extr$minimum[loc.minimum] <- "yes"

    return(df.extr)

    }
