#' Identify minima in a data frame
#'
#' Identify local extrema in a data frame
#'
#' @param df A \code{data.frame} generated by the \code{load.data} function.
#' @param threshold An integer defining threshold for local extrema identification
#'
#' @return A list containing full data df, last local minimum and maximum records, upper and lower sell zone boundary
#'
#' @export

upside.maximizer <- function(stocks, from = "2020-08-01", span_min = 11, span_max = 11) {

    full.df <- load.data(stocks = stocks, from = from)

    minima.df <- dplyr::filter(identify.minima(df = full.df, span = span_min), minimum == "yes")

    maxima.df <- dplyr::filter(identify.maxima(df = full.df, span = span_max), maximum == "yes")

    output.list <- list(
        "data" = full.df,
        "loc.min" = minima.df,
        "loc.max" = maxima.df
    )

    return(output.list)

}
