#' Identify minima in a data frame
#'
#' Identify local extrema in a data frame
#'
#' @param df A \code{data.frame} generated by the \code{load.data} function.
#' @param threshold An integer defining threshold for local extrema identification
#'
#' @return A list containing full data df, last local minimum and maximum records, upper and lower sell zone boundary
#'
#' @import dplyr
#' @export

upside.maximizer <- function(stocks, from = "2020-08-01", span = 11, sell_upper = 0.2, sell_lower = 0.4,...) {

    loaded.df <- load.data(stocks = stocks, from = from)

    minima.df <- identify.minima(df = loaded.df, span = span)

    last.min <- tail(dplyr::filter(minima.df, minimum == "yes"), 1)

    min.val <- last.min$close

    past.min <- dplyr::filter(minima.df, date > last.min$date)

    max.val <- max(past.min$close)

    last.max <- dplyr::filter(past.min, close == max.val)

    range.up <- max.val - (max.val - min.val) * sell_upper
    range.dn <- max.val - (max.val - min.val) * sell_lower

    output.list <- list(
        "data" = minima.df,
        "last.min" = last.min,
        "last.max" = last.max,
        "range.up" = range.up,
        "range.dn" = range.dn
    )

    return(output.list)

}
